language: node_js
node_js: "8"
branches:
  only:
  - master
cache:
  directories:
    - node_modules
  
install:
  - npm install -g firebase-tools

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
